arch:
  - arm64

addons:
  hosts:
    - node1

scripts:

  - cd ../
  - wget https://github.com/kunpengcompute/KAEdriver/releases/download/v1.2.8-beta.1/Kunpeng_KAE_driver-1.2.8-beta.1.tar.gz
  - tar -zxf Kunpeng_KAE_driver-1.2.8-beta.1.tar.gz
  - cd Kunpeng_KAE_driver/warpdrive
  - sudo sh autogen.sh 
  - sudo ./configure 
  - sudo make 
  - sudo make install
  
  - cd ../../
  - wget https://www.zlib.net/zlib-1.2.11.tar.gz
  - tar -zxf zlib-1.2.11.tar.gz
  - cd zlib-1.2.11
  - sudo patch -Np1 < ../KAEzip/kunpeng_zlib_1.2.8.patch
  - sudo ./configure --prefix=/usr/local/zlib
  - sudo make -j10
  - sudo make install
  